import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import { 
  Calendar, 
  Clock, 
  TrendingUp, 
  Heart, 
  MessageCircle,
  Sparkles,
  ChevronRight,
  Share2,
  Download,
  Loader2,
  RefreshCw
} from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { CalmCard } from "@/components/shared/CalmCard";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { useTranslation } from "@/hooks/useTranslation";
import { format } from "date-fns";
import { de } from "date-fns/locale";

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface SummaryData {
  summary: string;
  emotionalThemes: string[];
  nextStep: string;
  moodProgression: {
    start: string;
    end: string;
    insight: string;
  };
}

interface SessionMeta {
  startTime: Date;
  messageCount: number;
}

const SUMMARY_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-summary`;

export default function Summary() {
  const [summaryData, setSummaryData] = useState<SummaryData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [sessionMeta, setSessionMeta] = useState<SessionMeta | null>(null);
  const navigate = useNavigate();
  const location = useLocation();
  const { toast } = useToast();
  const { t, language } = useTranslation();

  const dateLocale = language === "de" ? de : undefined;

  // Get messages from navigation state or localStorage
  const getMessages = (): Message[] => {
    if (location.state?.messages) {
      return location.state.messages;
    }
    try {
      const stored = localStorage.getItem("soulvay-chat-messages");
      if (stored) {
        return JSON.parse(stored);
      }
    } catch {
      // Ignore parse errors
    }
    return [];
  };

  const generateSummary = async () => {
    const messages = getMessages();
    
    if (messages.length < 2) {
      toast({
        title: t("summary.notEnough"),
        description: t("summary.haveAChatFirst"),
        variant: "destructive",
      });
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    setSessionMeta({
      startTime: new Date(),
      messageCount: messages.filter(m => m.role === "user").length,
    });

    try {
      // Get auth token for authenticated request
      const { supabase } = await import("@/integrations/supabase/client");
      const { data: { session } } = await supabase.auth.getSession();
      const authToken = session?.access_token || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

      const response = await fetch(SUMMARY_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${authToken}`,
          apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
        },
        body: JSON.stringify({ messages, language }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || "Failed to generate summary");
      }

      const data = await response.json();
      setSummaryData(data);
    } catch (error) {
      if (import.meta.env.DEV) console.error("Summary error:", error);
      toast({
        title: t("summary.couldntGenerate"),
        description: t("summary.tryAgain"),
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    generateSummary();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleExport = () => {
    if (!summaryData) return;

    const exportText = `
Soulvay ${t("summary.title")}
========================
${language === "de" ? "Datum" : "Date"}: ${format(new Date(), "MMMM d, yyyy 'at' h:mm a", { locale: dateLocale })}

${t("summary.whatWeDiscussed")}
-----------------
${summaryData.summary}

${t("summary.keyThemes")}
--------------------
${summaryData.emotionalThemes.map((theme, i) => `${i + 1}. ${theme}`).join("\n")}

${t("summary.moodJourney")}
------------
${summaryData.moodProgression.start} → ${summaryData.moodProgression.end}
${summaryData.moodProgression.insight}

${t("summary.yourNextStep")}
-------------------
${summaryData.nextStep}

---
Generated by Soulvay
    `.trim();

    const blob = new Blob([exportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `soulvay-summary-${format(new Date(), "yyyy-MM-dd")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: t("summary.exported"),
      description: t("summary.downloaded"),
    });
  };

  const handleShare = async () => {
    if (!summaryData) return;

    const shareText = language === "de" 
      ? `Meine Soulvay-Sitzung behandelte: ${summaryData.emotionalThemes.slice(0, 2).join(" und ")}. Mein nächster Schritt: ${summaryData.nextStep}`
      : `My Soulvay session touched on: ${summaryData.emotionalThemes.slice(0, 2).join(" and ")}. My next step: ${summaryData.nextStep}`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Soulvay ${t("summary.title")}`,
          text: shareText,
        });
      } catch {
        // User cancelled or share failed
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast({
        title: t("summary.copiedToClipboard"),
        description: t("summary.pasteAnywhere"),
      });
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background pb-24">
        <PageHeader 
          title={t("summary.title")} 
          subtitle={t("summary.generating")}
          showBack 
          backTo="/chat"
        />
        <div className="flex flex-col items-center justify-center h-[60vh] gap-4">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          >
            <Loader2 className="w-8 h-8 text-primary" />
          </motion.div>
          <p className="text-muted-foreground text-sm">{t("summary.creating")}</p>
        </div>
      </div>
    );
  }

  if (!summaryData) {
    return (
      <div className="min-h-screen bg-background pb-24">
        <PageHeader 
          title={t("summary.title")} 
          showBack 
          backTo="/chat"
        />
        <div className="flex flex-col items-center justify-center h-[60vh] gap-4 px-4 text-center">
          <MessageCircle className="w-12 h-12 text-muted-foreground/50" />
          <p className="text-muted-foreground">{t("summary.noConversation")}</p>
          <Button onClick={() => navigate("/chat")}>{t("summary.startConversation")}</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background pb-24">
      <PageHeader 
        title={t("summary.title")} 
        subtitle={format(new Date(), "MMMM d, yyyy", { locale: dateLocale })}
        showBack 
        backTo="/chat"
      />

      <div className="px-4 py-4 max-w-lg mx-auto">
        {/* Session overview */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6"
        >
          <CalmCard variant="calm">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center">
                <MessageCircle className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground">{t("summary.chatSession")}</h3>
                <div className="flex items-center gap-3 text-xs text-muted-foreground">
                  {sessionMeta && (
                    <>
                      <span className="flex items-center gap-1">
                        <MessageCircle className="w-3 h-3" /> {sessionMeta.messageCount} {t("summary.messages")}
                      </span>
                    </>
                  )}
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" /> {t("summary.todayAt")} {format(new Date(), "h:mm a", { locale: dateLocale })}
                  </span>
                </div>
              </div>
            </div>
          </CalmCard>
        </motion.div>

        {/* Summary */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-3">{t("summary.whatWeDiscussed")}</h2>
          <CalmCard variant="elevated">
            <p className="text-sm text-foreground/90 leading-relaxed">
              {summaryData.summary}
            </p>
          </CalmCard>
        </motion.div>

        {/* Emotional themes */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="mb-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-3">{t("summary.keyThemes")}</h2>
          <CalmCard variant="elevated">
            <div className="flex flex-wrap gap-2">
              {summaryData.emotionalThemes.map((theme, index) => (
                <span
                  key={index}
                  className="px-3 py-1.5 bg-primary-soft text-primary text-xs font-medium rounded-full"
                >
                  {theme}
                </span>
              ))}
            </div>
          </CalmCard>
        </motion.div>

        {/* Mood insight */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mb-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-3">{t("summary.moodJourney")}</h2>
          <CalmCard variant="gentle">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="text-3xl">{summaryData.moodProgression.start}</span>
                <ChevronRight className="w-4 h-4 text-muted-foreground" />
                <span className="text-3xl">{summaryData.moodProgression.end}</span>
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground">
                  {summaryData.moodProgression.insight}
                </p>
              </div>
            </div>
          </CalmCard>
        </motion.div>

        {/* Next step */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25 }}
          className="mb-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-3">{t("summary.yourNextStep")}</h2>
          <CalmCard variant="default" className="border-primary/20 bg-primary-soft/30">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                <Sparkles className="w-5 h-5 text-primary" />
              </div>
              <p className="text-sm text-foreground/90 leading-relaxed pt-2">
                {summaryData.nextStep}
              </p>
            </div>
          </CalmCard>
        </motion.div>

        {/* Suggested exercises */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mb-8"
        >
          <h2 className="text-lg font-semibold text-foreground mb-3">{t("summary.helpfulExercises")}</h2>
          <div className="space-y-3">
            <CalmCard 
              variant="default" 
              className="cursor-pointer hover:shadow-card transition-shadow"
              onClick={() => navigate("/toolbox")}
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Heart className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1">
                  <p className="font-medium text-foreground">{t("summary.breathingExercise")}</p>
                  <p className="text-xs text-muted-foreground">1 min • {t("summary.calmYourMind")}</p>
                </div>
                <ChevronRight className="w-4 h-4 text-muted-foreground" />
              </div>
            </CalmCard>

            <CalmCard 
              variant="default" 
              className="cursor-pointer hover:shadow-card transition-shadow"
              onClick={() => navigate("/journal")}
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center">
                  <TrendingUp className="w-5 h-5 text-accent" />
                </div>
                <div className="flex-1">
                  <p className="font-medium text-foreground">{t("summary.journalThoughts")}</p>
                  <p className="text-xs text-muted-foreground">5 min • {t("summary.reflectDeeper")}</p>
                </div>
                <ChevronRight className="w-4 h-4 text-muted-foreground" />
              </div>
            </CalmCard>
          </div>
        </motion.div>

        {/* Actions */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35 }}
          className="flex gap-3"
        >
          <Button variant="outline" className="flex-1" onClick={handleShare}>
            <Share2 className="w-4 h-4 mr-2" />
            {t("common.share")}
          </Button>
          <Button variant="outline" className="flex-1" onClick={handleExport}>
            <Download className="w-4 h-4 mr-2" />
            {t("common.export")}
          </Button>
        </motion.div>

        {/* Regenerate */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-4 text-center"
        >
          <Button 
            variant="ghost" 
            size="sm" 
            onClick={generateSummary}
            className="text-muted-foreground"
          >
            <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            {t("summary.regenerate")}
          </Button>
        </motion.div>
      </div>
    </div>
  );
}
